language: node_js
node_js:
  - "node"

before_script:
  - npm install -g gulp
  - npm --prefix ./server install ./server
  - npm install ./server --only=dev

script: gulp --gulpfile server/gulpfile.js test

